window.STYLE_CATALOG = [
  { name: "Claude", slug: "claude", category: "AI 与大模型平台", description: "Anthropic 的 AI 助手。暖陶土色点缀，干净的编辑式排版。", sourceUrl: "https://getdesign.md/claude/design-md" },
  { name: "Cohere", slug: "cohere", category: "AI 与大模型平台", description: "企业级 AI 平台。高饱和渐变，数据密集型仪表盘气质。", sourceUrl: "https://getdesign.md/cohere/design-md" },
  { name: "ElevenLabs", slug: "elevenlabs", category: "AI 与大模型平台", description: "AI 语音平台。电影感深色界面，带音波可视化气质。", sourceUrl: "https://getdesign.md/elevenlabs/design-md" },
  { name: "Minimax", slug: "minimax", category: "AI 与大模型平台", description: "AI 模型提供商。大胆深色界面，配霓虹强调。", sourceUrl: "https://getdesign.md/minimax/design-md" },
  { name: "Mistral AI", slug: "mistral.ai", category: "AI 与大模型平台", description: "开源权重大模型提供商。法式工程极简，偏紫色调。", sourceUrl: "https://getdesign.md/mistral.ai/design-md" },
  { name: "Ollama", slug: "ollama", category: "AI 与大模型平台", description: "本地运行大模型。终端优先，黑白极简。", sourceUrl: "https://getdesign.md/ollama/design-md" },
  { name: "OpenCode AI", slug: "opencode.ai", category: "AI 与大模型平台", description: "AI 编码平台。开发者导向的深色主题。", sourceUrl: "https://getdesign.md/opencode.ai/design-md" },
  { name: "Replicate", slug: "replicate", category: "AI 与大模型平台", description: "通过 API 运行机器学习模型。白色画布，代码感强。", sourceUrl: "https://getdesign.md/replicate/design-md" },
  { name: "RunwayML", slug: "runwayml", category: "AI 与大模型平台", description: "AI 视频生成平台。电影感深色界面，媒体内容丰富。", sourceUrl: "https://getdesign.md/runwayml/design-md" },
  { name: "Together AI", slug: "together.ai", category: "AI 与大模型平台", description: "开源 AI 基础设施。技术蓝图式设计语言。", sourceUrl: "https://getdesign.md/together.ai/design-md" },
  { name: "VoltAgent", slug: "voltagent", category: "AI 与大模型平台", description: "AI Agent 框架。虚空黑画布，祖母绿点缀，终端原生感。", sourceUrl: "https://getdesign.md/voltagent/design-md" },
  { name: "xAI", slug: "x.ai", category: "AI 与大模型平台", description: "Elon Musk 的 AI 实验室。黑白极简，未来感强。", sourceUrl: "https://getdesign.md/x.ai/design-md" },
  { name: "Cursor", slug: "cursor", category: "开发工具与 IDE", description: "AI 优先代码编辑器。流畅深色界面，带渐变点缀。", sourceUrl: "https://getdesign.md/cursor/design-md" },
  { name: "Expo", slug: "expo", category: "开发工具与 IDE", description: "React Native 平台。深色主题、紧凑字距、强代码感。", sourceUrl: "https://getdesign.md/expo/design-md" },
  { name: "Lovable", slug: "lovable", category: "开发工具与 IDE", description: "AI 全栈构建器。活泼渐变，亲和的开发者审美。", sourceUrl: "https://getdesign.md/lovable/design-md" },
  { name: "Raycast", slug: "raycast", category: "开发工具与 IDE", description: "效率启动器。光滑深色外壳，鲜艳渐变强调。", sourceUrl: "https://getdesign.md/raycast/design-md" },
  { name: "Superhuman", slug: "superhuman", category: "开发工具与 IDE", description: "高速邮件客户端。高级感深色界面，键盘优先，紫色辉光。", sourceUrl: "https://getdesign.md/superhuman/design-md" },
  { name: "Vercel", slug: "vercel", category: "开发工具与 IDE", description: "前端部署平台。黑白精密感，Geist 字体气质。", sourceUrl: "https://getdesign.md/vercel/design-md" },
  { name: "Warp", slug: "warp", category: "开发工具与 IDE", description: "现代终端。深色 IDE 风格界面，块状命令交互。", sourceUrl: "https://getdesign.md/warp/design-md" },
  { name: "ClickHouse", slug: "clickhouse", category: "后端、数据库与 DevOps", description: "高速分析型数据库。黄色强调，技术文档风。", sourceUrl: "https://getdesign.md/clickhouse/design-md" },
  { name: "Composio", slug: "composio", category: "后端、数据库与 DevOps", description: "工具集成平台。现代深色界面，配彩色集成图标。", sourceUrl: "https://getdesign.md/composio/design-md" },
  { name: "HashiCorp", slug: "hashicorp", category: "后端、数据库与 DevOps", description: "基础设施自动化。企业级黑白极简。", sourceUrl: "https://getdesign.md/hashicorp/design-md" },
  { name: "MongoDB", slug: "mongodb", category: "后端、数据库与 DevOps", description: "文档数据库。绿色叶形品牌元素，开发者文档导向。", sourceUrl: "https://getdesign.md/mongodb/design-md" },
  { name: "PostHog", slug: "posthog", category: "后端、数据库与 DevOps", description: "产品分析平台。活泼刺猬品牌感，友好的开发者深色界面。", sourceUrl: "https://getdesign.md/posthog/design-md" },
  { name: "Sanity", slug: "sanity", category: "后端、数据库与 DevOps", description: "无头 CMS。红色强调，内容优先的编辑式布局。", sourceUrl: "https://getdesign.md/sanity/design-md" },
  { name: "Sentry", slug: "sentry", category: "后端、数据库与 DevOps", description: "错误监控平台。深色仪表盘，数据密集，粉紫点缀。", sourceUrl: "https://getdesign.md/sentry/design-md" },
  { name: "Supabase", slug: "supabase", category: "后端、数据库与 DevOps", description: "开源 Firebase 替代方案。深色祖母绿主题，代码优先。", sourceUrl: "https://getdesign.md/supabase/design-md" },
  { name: "Cal.com", slug: "cal", category: "效率与 SaaS", description: "开源排程工具。中性干净，开发者导向的简洁感。", sourceUrl: "https://getdesign.md/cal/design-md" },
  { name: "Intercom", slug: "intercom", category: "效率与 SaaS", description: "客户消息平台。友好的蓝色系，对话式界面模式。", sourceUrl: "https://getdesign.md/intercom/design-md" },
  { name: "Linear", slug: "linear.app", category: "效率与 SaaS", description: "面向工程团队的项目管理。极简、精确、紫色强调。", sourceUrl: "https://getdesign.md/linear.app/design-md" },
  { name: "Mintlify", slug: "mintlify", category: "效率与 SaaS", description: "文档平台。干净、绿色强调、阅读优化。", sourceUrl: "https://getdesign.md/mintlify/design-md" },
  { name: "Notion", slug: "notion", category: "效率与 SaaS", description: "一体化工作空间。温和极简、衬线标题、柔和表面。", sourceUrl: "https://getdesign.md/notion/design-md" },
  { name: "Resend", slug: "resend", category: "效率与 SaaS", description: "面向开发者的邮件 API。极简深色主题，等宽字细节。", sourceUrl: "https://getdesign.md/resend/design-md" },
  { name: "Zapier", slug: "zapier", category: "效率与 SaaS", description: "自动化平台。暖橙色调，友好的插画驱动感。", sourceUrl: "https://getdesign.md/zapier/design-md" },
  { name: "Airtable", slug: "airtable", category: "设计与创意工具", description: "表格数据库混合工具。多彩、友好、结构化数据美感。", sourceUrl: "https://getdesign.md/airtable/design-md" },
  { name: "Clay", slug: "clay", category: "设计与创意工具", description: "创意机构风格。有机形状、柔和渐变、强艺术指导感。", sourceUrl: "https://getdesign.md/clay/design-md" },
  { name: "Figma", slug: "figma", category: "设计与创意工具", description: "协作设计工具。高彩度多色，活泼但专业。", sourceUrl: "https://getdesign.md/figma/design-md" },
  { name: "Framer", slug: "framer", category: "设计与创意工具", description: "网站构建器。大胆黑蓝配色，动效优先，设计感强。", sourceUrl: "https://getdesign.md/framer/design-md" },
  { name: "Miro", slug: "miro", category: "设计与创意工具", description: "视觉协作工具。亮黄色点缀，无限画布气质。", sourceUrl: "https://getdesign.md/miro/design-md" },
  { name: "Webflow", slug: "webflow", category: "设计与创意工具", description: "可视化建站工具。蓝色强调，精致营销站审美。", sourceUrl: "https://getdesign.md/webflow/design-md" },
  { name: "Binance", slug: "binance", category: "金融科技与加密", description: "加密货币交易所。币安黄配黑白底，交易大厅般紧迫感。", sourceUrl: "https://getdesign.md/binance/design-md" },
  { name: "Coinbase", slug: "coinbase", category: "金融科技与加密", description: "加密货币交易所。干净蓝色识别，强调信任与机构感。", sourceUrl: "https://getdesign.md/coinbase/design-md" },
  { name: "Kraken", slug: "kraken", category: "金融科技与加密", description: "加密交易平台。紫色强调深色界面，数据密集型仪表盘。", sourceUrl: "https://getdesign.md/kraken/design-md" },
  { name: "Mastercard", slug: "mastercard", category: "金融科技与加密", description: "全球支付网络。暖奶油色画布、轨道药丸形态、编辑式温度。", sourceUrl: "https://getdesign.md/mastercard/design-md" },
  { name: "Revolut", slug: "revolut", category: "金融科技与加密", description: "数字银行。流畅深色界面，渐变卡片，金融科技精密感。", sourceUrl: "https://getdesign.md/revolut/design-md" },
  { name: "Stripe", slug: "stripe", category: "金融科技与加密", description: "支付基础设施。标志性紫色渐变，轻量字重的优雅感。", sourceUrl: "https://getdesign.md/stripe/design-md" },
  { name: "Wise", slug: "wise", category: "金融科技与加密", description: "国际汇款平台。明亮绿色强调，清晰且友好。", sourceUrl: "https://getdesign.md/wise/design-md" },
  { name: "Airbnb", slug: "airbnb", category: "电商与零售", description: "旅行平台。暖珊瑚色点缀，摄影驱动，圆角界面。", sourceUrl: "https://getdesign.md/airbnb/design-md" },
  { name: "Meta", slug: "meta", category: "电商与零售", description: "科技零售商店。摄影优先，明暗双表面，Meta 蓝 CTA。", sourceUrl: "https://getdesign.md/meta/design-md" },
  { name: "Nike", slug: "nike", category: "电商与零售", description: "运动零售。黑白单色界面，巨大 Futura 大写标题，全屏摄影。", sourceUrl: "https://getdesign.md/nike/design-md" },
  { name: "Shopify", slug: "shopify", category: "电商与零售", description: "电商平台。深色电影感主导，霓虹绿点缀，超轻展示字体。", sourceUrl: "https://getdesign.md/shopify/design-md" },
  { name: "Starbucks", slug: "starbucks", category: "电商与零售", description: "咖啡零售旗舰。四层大地绿色系统，暖奶油画布，SoDoSans 字体气质。", sourceUrl: "https://getdesign.md/starbucks/design-md" },
  { name: "Apple", slug: "apple", category: "媒体与消费科技", description: "消费电子。高级留白，SF Pro 气质，电影感图像。", sourceUrl: "https://getdesign.md/apple/design-md" },
  { name: "IBM", slug: "ibm", category: "媒体与消费科技", description: "企业科技。Carbon 设计系统，结构化蓝色体系。", sourceUrl: "https://getdesign.md/ibm/design-md" },
  { name: "NVIDIA", slug: "nvidia", category: "媒体与消费科技", description: "GPU 计算平台。绿色与黑色能量感，技术力量审美。", sourceUrl: "https://getdesign.md/nvidia/design-md" },
  { name: "Pinterest", slug: "pinterest", category: "媒体与消费科技", description: "视觉发现平台。红色点缀，瀑布流网格，图片优先。", sourceUrl: "https://getdesign.md/pinterest/design-md" },
  { name: "PlayStation", slug: "playstation", category: "媒体与消费科技", description: "游戏主机零售。三层表面布局，青色悬停缩放交互。", sourceUrl: "https://getdesign.md/playstation/design-md" },
  { name: "SpaceX", slug: "spacex", category: "媒体与消费科技", description: "航天科技。黑白强对比，全屏图像，未来感。", sourceUrl: "https://getdesign.md/spacex/design-md" },
  { name: "Spotify", slug: "spotify", category: "媒体与消费科技", description: "音乐流媒体。深色底上的鲜绿强调，粗体标题，专辑封面驱动。", sourceUrl: "https://getdesign.md/spotify/design-md" },
  { name: "The Verge", slug: "theverge", category: "媒体与消费科技", description: "科技媒体。酸性薄荷与紫外色点缀，Manuka 展示字体。", sourceUrl: "https://getdesign.md/theverge/design-md" },
  { name: "Uber", slug: "uber", category: "媒体与消费科技", description: "出行平台。黑白强对比，紧凑排版，城市能量感。", sourceUrl: "https://getdesign.md/uber/design-md" },
  { name: "Vodafone", slug: "vodafone", category: "媒体与消费科技", description: "全球通信品牌。纪念碑式大写标题，Vodafone 红章节条带。", sourceUrl: "https://getdesign.md/vodafone/design-md" },
  { name: "WIRED", slug: "wired", category: "媒体与消费科技", description: "科技杂志。纸白色报刊密度，自定义衬线，墨蓝色链接。", sourceUrl: "https://getdesign.md/wired/design-md" },
  { name: "BMW", slug: "bmw", category: "汽车", description: "豪华汽车。深色高端表面，精密的德式工程感。", sourceUrl: "https://getdesign.md/bmw/design-md" },
  { name: "Bugatti", slug: "bugatti", category: "汽车", description: "超跑品牌。电影黑画布，黑白克制，纪念碑式展示字体。", sourceUrl: "https://getdesign.md/bugatti/design-md" },
  { name: "Ferrari", slug: "ferrari", category: "汽车", description: "豪华汽车。黑白明暗对照的编辑感，法拉利红极简点缀。", sourceUrl: "https://getdesign.md/ferrari/design-md" },
  { name: "Lamborghini", slug: "lamborghini", category: "汽车", description: "豪华汽车。纯黑殿堂感画布，金色点缀，定制新怪诞体。", sourceUrl: "https://getdesign.md/lamborghini/design-md" },
  { name: "Renault", slug: "renault", category: "汽车", description: "法国汽车品牌。鲜明极光渐变，NouvelR 字体，零圆角按钮。", sourceUrl: "https://getdesign.md/renault/design-md" },
  { name: "Tesla", slug: "tesla", category: "汽车", description: "电动车品牌。极致减法，全屏电影摄影，Universal Sans 气质。", sourceUrl: "https://getdesign.md/tesla/design-md" }
];
